In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
l=WordNetLemmatizer()
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
stop_words=set(stopwords.words('english'))
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

[nltk_data] Downloading package stopwords to C:\Users\Nischay
[nltk_data]     kapoor\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [153]:
#Loading the Dataset
df=pd.read_csv("Education.csv")

In [154]:
df.head()

Text     Label
0  The impact of educational reforms remains unce...  positive
1  Critics argue that recent improvements in the ...  negative
2  Innovative teaching methods have led to unexpe...  positive
3  Despite budget constraints, the school has man...  positive
4  The true effectiveness of online learning plat...  negative

Exploratory Data Analysis (EDA)

In [155]:
df.isnull().sum()

Text     0
Label    0
dtype: int64

In [156]:
df.duplicated().sum()

0

In [157]:
df.shape

(52, 2)

In [158]:
df.describe()

Text     Label
count                                                  52        52
unique                                                 52         2
top     The impact of educational reforms remains unce...  positive
freq                                                    1        26

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Text    52 non-null     object
 1   Label   52 non-null     object
dtypes: object(2)
memory usage: 964.0+ bytes


In [160]:
df['Label'].value_counts()   

Label
positive    26
negative    26
Name: count, dtype: int64

 Data Preprocessing

In [161]:
import re
corpus=[]
for i in range(0,len(df)):
    words=re.sub('[^a-zA-Z]',' ',df['Text'][i])
    words=words.lower()
    words=words.split()
    words=[l.lemmatize(word) for word in words if word not in stop_words]
    words=' '.join(words)
    corpus.append(words)

In [162]:
X=corpus
y=df['Label']

In [163]:
#Splitting the Data
x_train, x_test, y_train, y_test = train_test_split(corpus,y, test_size=0.3, random_state=42)

In [120]:
from sklearn.ensemble import RandomForestClassifier

In [121]:
#using Tfidf and Random Forest
classifier = Pipeline([('tfidf', TfidfVectorizer()), ('classifier', RandomForestClassifier())])
classifier.fit(x_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier', RandomForestClassifier())])

In [122]:
#Model Evaluation
y_pred_tf = classifier.predict(x_test)
accuracy_score(y_test, y_pred_tf)

0.3125

In [123]:
confusion_matrix(y_test, y_pred_tf)

array([[2, 4],
       [7, 3]], dtype=int64)

In [135]:
#using bow and Random Forest
from sklearn.feature_extraction.text import CountVectorizer
classifier = Pipeline([('bow', CountVectorizer()), ('classifier', RandomForestClassifier())])
classifier.fit(x_train, y_train)

Pipeline(steps=[('bow', CountVectorizer()),
                ('classifier', RandomForestClassifier())])

In [136]:
y_pred_bow = classifier.predict(x_test)
accuracy_score(y_test, y_pred_bow)

0.3125

In [137]:
confusion_matrix(y_test, y_pred_bow)

array([[4, 2],
       [9, 1]], dtype=int64)

In [149]:
from sklearn.naive_bayes import MultinomialNB

In [150]:
#using Tfidf and Naive Baiys
classifier = Pipeline([('tfidf', TfidfVectorizer()), ('classifier', MultinomialNB())])
classifier.fit(x_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('classifier', MultinomialNB())])

In [151]:
y_pred_nb = classifier.predict(x_test)
accuracy_score(y_test, y_pred_nb)

0.3125

In [152]:
confusion_matrix(y_test, y_pred_nb)

array([[3, 3],
       [8, 2]], dtype=int64)

In [164]:
from sklearn.svm import SVC

In [165]:
#using Tfidf and Support Vector Classifier
classifier = Pipeline([('tfidf', TfidfVectorizer()), ('classifier', SVC())])
classifier.fit(x_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('classifier', SVC())])

In [166]:
y_pred_svc = classifier.predict(x_test)
accuracy_score(y_test, y_pred_svc)

0.375

In [167]:
confusion_matrix(y_test, y_pred_svc)

array([[5, 1],
       [9, 1]], dtype=int64)

In [168]:
#using BOW and SVC
classifier = Pipeline([('bow', CountVectorizer()), ('classifier', SVC())])
classifier.fit(x_train, y_train)

Pipeline(steps=[('bow', CountVectorizer()), ('classifier', SVC())])

In [169]:
y_pred_sv = classifier.predict(x_test)
accuracy_score(y_test, y_pred_sv)

0.3125

In [170]:
confusion_matrix(y_test, y_pred_sv)

array([[4, 2],
       [9, 1]], dtype=int64)

In [171]:
from sklearn.linear_model import LogisticRegression

In [172]:
#using Tfidf and Logistic Regression
classifier = Pipeline([('tfidf', TfidfVectorizer()), ('classifier', LogisticRegression())])
classifier.fit(x_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier', LogisticRegression())])

In [173]:
y_pred_lr = classifier.predict(x_test)
accuracy_score(y_test, y_pred_lr)

0.375

In [174]:
confusion_matrix(y_test, y_pred_lr)

array([[5, 1],
       [9, 1]], dtype=int64)

In [175]:
classifier.predict(['The impact of educational reforms remains uncertain despite extensive research.'])

array(['positive'], dtype=object)